function projectPaths = setup_project_paths()
% Add the project subfolders to the MATLAB path and return the key locations.
% Keeping this centralized makes it easier to reorganize files without
% scattering hard-coded relative paths across scripts.

persistent cachedPaths

if isempty(cachedPaths)
    projectRoot = fileparts(mfilename('fullpath'));

    cachedPaths = struct( ...
        'rootDir', projectRoot, ...
        'aerodynamicsDir', fullfile(projectRoot, 'aerodynamics'), ...
        'finalizeDir', fullfile(projectRoot, 'finalize'), ...
        'gasdynamicsDir', fullfile(projectRoot, 'gasdynamics'), ...
        'geometryDir', fullfile(projectRoot, 'geometry'), ...
        'initializeDir', fullfile(projectRoot, 'initialize'), ...
        'optimizationDir', fullfile(projectRoot, 'optimization'), ...
        'postprocessDir', fullfile(projectRoot, 'postprocess'), ...
        'thermoDir', fullfile(projectRoot, 'thermo'), ...
        'utilitiesDir', fullfile(projectRoot, 'utilities'), ...
        'dataDir', fullfile(projectRoot, 'data'), ...
        'resultsDir', fullfile(projectRoot, 'results'));

    addpath(cachedPaths.rootDir, ...
        cachedPaths.aerodynamicsDir, ...
        cachedPaths.finalizeDir, ...
        cachedPaths.gasdynamicsDir, ...
        cachedPaths.geometryDir, ...
        cachedPaths.initializeDir, ...
        cachedPaths.optimizationDir, ...
        cachedPaths.postprocessDir, ...
        cachedPaths.thermoDir, ...
        cachedPaths.utilitiesDir);
end

projectPaths = cachedPaths;
end
